version: '3.1'

services:
  rlc_php:
    container_name: rlc_php
    build:
      context: php-fpm
    volumes:
      - ../../:/var/www
    ports:
      - "80:8080"
      - "8081:8081"
  rlc_mysql_master:
    container_name: rlc_mysql_master
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '5baeQdaQVNgWSu8D'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'VKqtVqNr2xMWx34Q'
    ports:
      - '3306:3306'
    volumes:
      - rlc_mysql_master:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d

volumes:
  rlc_mysql_master:
